### ISSUE TITLE
rule #0 include an unknown policy name:nProxy

### ISSUE THREAD

**Issue by xfoxtbat** [Hackl0us/Surge-Rule-Snippets#1]
https://raw.githubusercontent.com/Hackl0us/Surge-Rule-Snippets/master/Surge.conf  直接用你的自用surge配置

填入自己的服务器2个proxy1和proxy2 都写一样的  填入自己的服务器   iso surge 和 mac surge 都报错

rule #0 include an unknown policy name:nProxy

把nproxy 改为DIRECT 

报错  rule #13   Unknown policy name: Proxy

**Comment by aborigine** [comment]
所有nProxy替换成proxy下面代理的名称试试

**Comment by Hackl0us** [comment]
@xfoxtbat 您好。
rule #0 include an unknown policy name:nProxy 表示您没有相关的策略组，您只需要添加或者批量替换nProxy为DIRECT即可解决问题。之所以设置nProxy这个单独的策略组，是因为Apple的部分服务器可代理可直连，比较特殊。

rule #13 Unknown policy name: Proxy
同样是缺少相同的策略名称：Proxy，您需要在[Proxy]或[Proxy Group]中添加相应的策略

**Comment by Hackl0us** [comment]
用户应明确[Proxy] [Proxy Group]等使用方法，才能正确配置Surge，建议先了解官方给出的配置文件范例，再进行配置编辑。使用策略/策略组必须在成[Proxy] 或 [Proxy Group]中出现，后文才可使用。

问题至此关闭。
