### ISSUE TITLE
没有过滤视频广告的规则？

### ISSUE THREAD

**Issue by benzBrake** [Hackl0us/Surge-Rule-Snippets#11]
優酷和搜狐都有GG

**Comment by Hackl0us** [comment]
为什么不仔细查看项目？
https://github.com/Hackl0us/Surge-Rule-Snippets/blob/master/%E5%AE%9E%E7%94%A8%E8%A7%84%E5%88%99%E7%89%87%E6%AE%B5/%E5%B1%8F%E8%94%BD%E8%A7%86%E9%A2%91%E5%B9%BF%E5%91%8A.txt
