### ISSUE TITLE
使用新浪微博国际版时加载速度缓慢

### ISSUE THREAD

**Issue by openviso** [Hackl0us/Surge-Rule-Snippets#12]
经检查发现api.weibo.cn 实际上走的代理

**Comment by Hackl0us** [comment]
您好，非常感谢您的测试和使用。
但是我刚才测试了一下我的规则，发现 api.weibo.cn 走的的确是**直连**而不是代理呀。

您是不是配置出现了一些问题呢？

![测试结果](https://cloud.githubusercontent.com/assets/10215166/26769436/97607bfa-49e1-11e7-9432-512441c95bd5.jpg)

**Comment by openviso** [comment]
不好意思，是我的配置弄错了

**Comment by Hackl0us** [comment]
好的，了解了。

如果有任何问题请继续提交 Issue，感谢您的支持。
