### ISSUE TITLE
【网易云音乐】【喜马拉雅】【京东】【淘宝】的启动广告亲测无法屏蔽

### ISSUE THREAD

**Issue by openviso** [Hackl0us/Surge-Rule-Snippets#13]

**Comment by Hackl0us** [comment]
您好，非常感谢您的使用和测试。
但是，我的规则本来就没有加入对您所提及的 App 的启动广告屏蔽规则……

我在项目主页对广告屏蔽相关做出了解释，您可以认真阅读一下。
感谢。
