### ISSUE TITLE
申请kyzyhello.com和kyzyhello.tk域名加入到gfwlist列表

### ISSUE THREAD

**Issue by kyzypm** [Hackl0us/Surge-Rule-Snippets#15]
因为某些原因总是被干扰，希望给用户提供更好的访问体验，谢谢啦，申请kyzyhello.com和kyzyhello.tk域名加入到gfwlist列表。

**Comment by Hackl0us** [comment]
您好，非常感谢您提交的申请。
但是 GFWList 这个项目不是我在维护。
另外，这两个网站是否被很多用户所访问，需求量很大吗？

**Comment by Hackl0us** [comment]
暂时关闭这个请求，如果有任何异议请重新打开 Issue，非常感谢~
