### ISSUE TITLE
请问WhatsApp.txt的数据来自哪里

### ISSUE THREAD

**Issue by ztechie** [Hackl0us/Surge-Rule-Snippets#17]
请问WhatsApp.txt的数据来自哪里

**Comment by Hackl0us** [comment]
WhatsApp 的 服务器 IP 地址段原来来自于：https://www.whatsapp.com/cidr.txt，是官方公布的资源。
但是显然现在已经被移除了，官方声明说将会移动到 https://fb.me/mpp_support

**Comment by ztechie** [comment]
mobile-ops@fb.com发邮件过去没人回复，显然这个cidr已经很久没更新了，有时候还是上不去

**Comment by iKenzo** [comment]
新的在这里
https://developers.facebook.com/docs/whatsapp/guides/network-requirements/
