### ISSUE TITLE
Lastpass 规则

### ISSUE THREAD

**Issue by iCasture** [Hackl0us/Surge-Rule-Snippets#2]
是否考虑增加针对 Lastpass 的规则？最近首次打开 Lastpass 保险库的速度特别慢，但是挂着 VPN 就基本秒开

**Comment by Hackl0us** [comment]
已经了解您的需求，我会准备相应规则。

**Comment by Hackl0us** [comment]
@iCasture 您好：

在版本v2.1.0中已经达成您的需求。[请参阅此处](https://github.com/Hackl0us/Surge-Rule-Snippets/blob/master/%E7%89%B9%E6%AE%8AApp%E4%BC%98%E5%8C%96/LastPass.txt)

此问题关闭，有任何问题请与我联系。或继续提交 Issue。
