### ISSUE TITLE
面向校园网的Proxy字段

### ISSUE THREAD

**Issue by sequencer** [Hackl0us/Surge-Rule-Snippets#3]
有个在校园网架设的代理
准备把学术性的网站都在校园网上走
方便下载论文之类的
不知道是否能接受这个PR？

**Comment by Hackl0us** [comment]
您好，我并不是很清楚您的需求。
论文网站例如中国知网？
如果校园网的代理支持类似Socks5协议，您可以尝试在PROXY字段填写服务器设置，然后论文地址填写制定服务器即可。

例如：
`DOMAIN,cnki.net,校园网代理策略名`

或者您可以使用专门的论文下载脚本尝试下载。

如果您对我的描述有任何疑问，或者我对您的需求理解错误，请您继续留言。

**Comment by womeimingzi11** [comment]
嗯，就是这么一个问题。比如一些常见的学术网站，比如：sciencedirect、springer 这些出版商的网站。不少学校都购买了数据库，需要用校园网访问。比如我在学校就用Direct 这样。建议整理一份这样的片段出来。或许我可以帮忙添加一些理工科的？

**Comment by Hackl0us** [comment]
@womeimingzi11 我可能需要您的协助，完成这个。我个人能力有限，而且不是很频繁使用这类东西。

**Comment by Hackl0us** [comment]
@womeimingzi11 已经修改并合并您的请求，感谢您为项目作出贡献。

此问题至此关闭。
