### ISSUE TITLE
IP-CIDR 部分的 PROXY 需要小写

### ISSUE THREAD

**Issue by greghe728** [Hackl0us/Surge-Rule-Snippets#4]
不然前后不一致会报错呀

**Comment by Hackl0us** [comment]
@greghe728 ，您好：

我也发现这个问题啦。目前已经解决，本问题导致`Surge`导入规则时提示未知的策略组。看到大家反馈后立刻修复此问题。

此问题关闭。如果有任何问题请与我取得联系，或者提交新的Issue，非常感谢。
