### ISSUE TITLE
ShadowRocket.conf "skip-Proxy" 大小写问题

### ISSUE THREAD

**Issue by ChrisCHEN05** [Hackl0us/Surge-Rule-Snippets#9]
ShadowRocket.conf 第五行的 "skip-Proxy" 中，Proxy 首字母大写时，其值不能导入 Shadowrocket 里配置文件对应的 “Skip Proxy” 下。若改为小写，即改成 "skip-proxy" 后，则正常。

**Comment by Hackl0us** [comment]
@ChrisCHEN05 非常感谢您的发现，我会立刻修正这个问题。
感谢您的耐心发现~~~~
